### PR TITLE
updating mincer version to fix sass issue

### PR DESCRIPTION
**Pull request by dmtaub**

### CODE REVIEW

**Comment by adunkman** [comment]
Looks like there are a few test failures.

**Comment by netsgnut** [comment]
It seems the jump between 1.2.4 and 1.2.5 causes some of the cryptic ENOENT errors, apart from the almost-routine hash differences.

**Comment by netsgnut** [comment]
Oh never mind, it seems to be fixed by changing the hash (see https://github.com/netsgnut/connect-assets/commit/a3986b4c28361d4e06c6ff360dd8afb9b09e2578).

FYI I have actually have a branch that bumps mincer, uglify-js and csswring that could supersede this one. However I was getting lazy and tested upon the unreleased mincer 1.3.0 instead (see https://github.com/netsgnut/mincer/tree/postcss4-compat and nodeca/mincer#200 for potentially how it could go).

I will do a PR once mincer 1.3.0 is released officially.

**Comment by dmtaub** [comment]
well i've updated the hashes

**Comment by netsgnut** [comment]
@dmtaub Agreed. That said I am still not sure why the hashes are changed every time `mincer` is updated.

**Comment by adunkman** [comment]
> FWIW, I think having hashes in the tests at all is a disincentive to trust the tests... 

Can you explain? My motivation for having them in the tests is that you should be explicit about changing assets — if you make a JavaScript-specific update and it changes a CSS file, I’m glad the tests fail. I’m open to change though if presented a solid argument! :)

**Comment by adunkman** [comment]
Merged #313 instead, since it included all of this and more! 

Thanks @dmtaub for the work, sorry these commits didn’t make it in, but at least your problem is fixed! :100:

**Pull request closed without merging**
