### PR TITLE
Bumping to Mincer 1.3.0, Csswring 3.0.5, Uglify JS 2.4.23, and more

### LINKED ISSUE #307: csswring 3.0.0 bug
Using a library called w2ui has a less style like so https://github.com/vitmalina/w2ui/blob/master/src/less/src/common.less#L84

```less
    input:not([type=button]), select, textarea {
        padding: 4px;
        border: @input-border;
        border-radius: 3px;
        color: @input-color;
        background-color: @input-background-color;
        line-height: normal;
        &:focus {
            outline-color: @input-focus-outline-color;    
        }
        &:disabled, &[readonly] {
            background-color: #f1f1f1;
            color: #777;
        }    
    }
```

Straight through less in development mode it comes out as:

```css
input:not([type=button]):disabled,
select:disabled,
textarea:disabled,
input:not([type=button])[readonly],
select[readonly],
textarea[readonly] {
  background-color: #f1f1f1;
  color: #777;
}
```

Through csswring, when the app is in production mode. 

```css
input:not([type=button]):disabled,select:disabled,textarea:disabled,input:not([type="button])[readonly"],select[readonly],textarea[readonly] {
    background-color: #f1f1f1;
    color: #777
}
```

This problem string in question

```css
input:not([type="button])[readonly"]
```

csswring 3.0.5 can parse this correctly. 
Updating my local connect-assets `package.json` to `"csswring": "~3.0.5"` fixed the issue.

Could the included csswring be updated to the latest patch release?

### PR DESCRIPTION
**Pull request by netsgnut**
This is a pretty large chunk of dependency bumps. Highlights include:
* mincer 1.2.4 -> 1.3.0
* uglify-js 2.4.16 -> 2.4.23
* argparse 0.1.16 -> 1.0.2
* csswring 3.0.0 -> 3.0.5

For dev dependencies:
* mocha 2.1.0 -> 2.2.5
* blanket 1.1.6 -> 1.1.7
* connect 3.3.4 -> 3.4.0

Once merged, this should close #307, #308, #310.
This PR supercedes #309, #312.

### CODE REVIEW

**Comment by netsgnut** [comment]
Hmm, better look at this a bit later today if possible. Just curious @adunkman, do you prefer them to be in separate commits or as one commit for all? Thanks.

**Comment by adunkman** [comment]
:heart: :heart: :heart: 

> Just curious @adunkman, do you prefer them to be in separate commits or as one commit for all?

Either is fine, assuming there wasn’t anything alarming in the changes in which I’d be concerned which update it was related to — but that’s not the case here, so whatever! 

Thanks for all the updates! :new:

**Comment by adunkman** [comment]
Published as `4.8.0`. Thanks, all! 

/cc @deployable @dapriett @dmtaub

**Comment by netsgnut** [comment]
Great! Glad we are now back on track with Mincer :smile:

**Pull request merged**
